name: Build and test

on: [push]

jobs:
    build-and-test-unix:
        name: Build and test on ${{matrix.os}}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                 submodules: recursive
            - name: Building Elrond Common Library project
              run: |
                cd elrond && \
                cmake -B./build -G "Unix Makefiles" . && \
                cmake --build ./build --target all -j 6 -- 
            - name: Run CMake
              run: cmake -B./build -G "Unix Makefiles" .
            - name: Build everything
              run: cmake --build ./build --target all -j 6 --
            - name: Run tests
              run: ctest -j6 -T test --output-on-failure --test-dir ./build

